---
- name: Install Docker
  hosts: all
  become: true
  tasks:
    - name: Install packages
      package:
        name:
          - docker
          - git
        state: present
    - name: Enable & start Docker
      service:
        name: docker
        state: started
        enabled: yes
    - name: Add ec2-user to docker group
      user:
        name: "{{ ansible_user | default('ec2-user') }}"
        groups: docker
        append: true
