---
- name: Install kubectl & Helm on Jenkins host
  hosts: jenkins
  become: true
  tasks:
    - name: Download kubectl
      get_url:
        url: "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
        force: no
    - name: Install Helm v3
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm
